In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df = pd.read_csv('df_final.csv')
df = df.drop('Unnamed: 0',axis=1)
df

,ehr,birth_date,diagnosis_date,death_date,er,her2,ki67,pr,pregnancy,birth,...,m_category,t_category_after_neoadj,n_category_after_neoadj,m_category_after_neoadj,stage_diagnosis,stage_after_neo,grade,ductal,lobular,neoadjuvant
0,10011773,05-07-1959,02-04-2015,NaN,0.0,0.0,19.0,1.0,0.0,0.0,...,0.0,SIN TRATAMIENTO,SIN TRATAMIENTO,SIN TRATAMIENTO,0,SIN TRATAMIENTO,1.0,0.0,0.0,0.0
1,10020495,02-10-1953,04-12-2017,NaN,1.0,0.0,9.0,0.0,0.0,0.0,...,0.0,SIN TRATAMIENTO,SIN TRATAMIENTO,SIN TRATAMIENTO,IA,SIN TRATAMIENTO,2.0,1.0,0.0,0.0
2,10030299,16-08-1966,27-06-2019,NaN,1.0,0.0,18.0,1.0,3.0,3.0,...,0.0,SIN TRATAMIENTO,SIN TRATAMIENTO,SIN TRATAMIENTO,IA,SIN TRATAMIENTO,1.0,1.0,0.0,0.0
3,10030824,03-03-1953,07-09-2018,NaN,1.0,0.0,18.0,1.0,0.0,0.0,...,0.0,2,2.0,0.0,IIIA,IIIA,3.0,0.0,1.0,1.0
4,10041592,06-07-1959,19-11-2018,NaN,0.0,0.0,65.0,0.0,0.0,0.0,...,0.0,4,0.0,0.0,IB,IA,2.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11162,99343880,23-08-1944,28-05-2018,NaN,1.0,0.0,68.0,1.0,2.0,2.0,...,1.0,SIN TRATAMIENTO,SIN TRATAMIENTO,SIN TRATAMIENTO,IA,SIN TRATAMIENTO,2.0,0.0,0.0,0.0
11163,99443402,17-06-1959,21-01-2018,NaN,1.0,0.0,22.0,0.0,0.0,0.0,...,1.0,SIN TRATAMIENTO,SIN TRATAMIENTO,SIN TRATAMIENTO,IIB,SIN TRATAMIENTO,3.0,0.0,1.0,0.0
11164,99656792,26-03-1976,23-07-2017,NaN,1.0,1.0,49.0,0.0,0.0,0.0,...,0.0,4,0.0,0,IA,SIN TRATAMIENTO,1.0,0.0,0.0,1.0
11165,99690760,21-07-1961,28-10-2013,NaN,1.0,0.0,20.0,1.0,1.0,1.0,...,0.0,SIN TRATAMIENTO,SIN TRATAMIENTO,SIN TRATAMIENTO,IA,SIN TRATAMIENTO,1.0,1.0,0.0,0.0
11166,99807703,06-08-1948,08-07-2017,NaN,1.0,0.0,11.0,1.0,1.0,1.0,...,0.0,4,0.0,0,IIIA,SIN TRATAMIENTO,2.0,0.0,1.0,1.0